// Generated by CoffeeScript 1.10.0
var $, Chosen,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

$ = jQuery;

$.fn.extend({
  chosen: function(options) {
    if (!AbstractChosen.browser_is_supported()) {
      return this;
    }
    return this.each(function(input_field) {
      var $this, chosen;
      $this = $(this);
      chosen = $this.data('chosen');
      if (options === 'destroy') {
        if (chosen instanceof Chosen) {
          chosen.destroy();
        }
        return;
      }
      if (!(chosen instanceof Chosen)) {
        $this.data('chosen', new Chosen(this, options));
      }
    });
  }
});

Chosen = (function(superClass) {
  extend(Chosen, superClass);

  function Chosen() {
    return Chosen.__super__.constructor.apply(this, arguments);
  }

  Chosen.prototype.setup = function() {
    this.form_field_jq = $(this.form_field);
    this.current_selectedIndex = this.form_field.selectedIndex;
    return this.is_rtl = this.form_field_jq.hasClass("chosen-rtl");
  };

  Chosen.prototype.set_up_html = function() {
    var container_classes, container_props;
    container_classes = ["chosen-container"];
    container_classes.push("chosen-container-" + (this.is_multiple ? "multi" : "single"));
    if (this.inherit_select_classes && this.form_field.className) {
      container_classes.push(this.form_field.className);
    }
    if (this.is_rtl) {
      container_classes.push("chosen-rtl");
    }
    container_props = {
      'class': container_classes.join(' '),
      'style': "width: " + (this.container_width()) + ";",
      'title': this.form_field.title
    };
    if (this.form_field.id.length) {
      container_props.id = this.form_field.id.replace(/[^\w]/g, '_') + "_chosen";
    }
    this.container = $("<div />", container_props);
    if (this.is_multiple) {
      this.container.html('<ul class="chosen-choices"><li class="search-field"><input type="text" value="' + this.default_text + '" class="default" autocomplete="off" style="width:25px;" /></li></ul><div class="chosen-drop"><ul class="chosen-results"></ul></div>');
    } else {
      this.container.html('<a class="chosen-single chosen-default"><span>' + this.default_text + '</span><div><b></b></div></a><div class="chosen-drop"><div class="chosen-search"><input type="text" autocomplete="off" /></div><ul class="chosen-results"></ul></div>');
    }
    this.form_field_jq.hide().after(this.container);
    this.dropdown = this.container.find('div.chosen-drop').first();
    this.search_field = this.container.find('input').first();
    this.search_results = this.container.find('ul.chosen-results').first();
    this.search_field_scale();
    this.search_no_results = this.container.find('li.no-results').first();
    if (this.is_multiple) {
      this.search_choices = this.container.find('ul.chosen-choices').first();
      this.search_container = this.container.find('li.search-field').first();
    } else {
      this.search_container = this.container.find('div.chosen-search').first();
      this.selected_item = this.container.find('.chosen-single').first();
    }
    this.results_build();
    this.set_tab_index();
    return this.set_label_behavior();
  };

  Chosen.prototype.on_ready = function() {
    return this.form_field_jq.trigger("chosen:ready", {
      chosen: this
    });
  };

  Chosen.prototype.register_observers = function() {
    this.container.bind('touchstart.chosen', (function(_this) {
      return function(evt) {
        _this.container_mousedown(evt);
        return evt.preventDefault();
      };
    })(this));
    this.container.bind('touchend.chosen', (function(_this) {
      return function(evt) {
        _this.container_mouseup(evt);
        return evt.preventDefault();
      };
    })(this));
    this.container.bind('mousedown.chosen', (function(_this) {
      return function(evt) {
        _this.container_mousedown(evt);
      };
    })(this));
    this.container.bind('mouseup.chosen', (function(_this) {
      return function(evt) {
        _this.container_mouseup(evt);
      };
    })(this));
    this.container.bind('mouseenter.chosen', (function(_this) {
      return function(evt) {
        _this.mouse_enter(evt);
      };
    })(this));
    this.container.bind('mouseleave.chosen', (function(_this) {
      return function(evt) {
        _this.mouse_leave(evt);
      };
    })(this));
    this.search_results.bind('mouseup.chosen', (function(_this) {
      return function(evt) {
        _this.search_results_mouseup(evt);
      };
    })(this));
    this.search_results.bind('mouseover.chosen', (function(_this) {
      return function(evt) {
        _this.search_results_mouseover(evt);
      };
    })(this));
    this.search_results.bind('mouseout.chosen', (function(_this) {
      return function(evt) {
        _this.search_results_mouseout(evt);
      };
    })(this));
    this.search_results.bind('mousewheel.chosen DOMMouseScroll.chosen', (function(_this) {
      return function(evt) {
        _this.search_results_mousewheel(evt);
      };
    })(this));
    this.search_results.bind('touchstart.chosen', (function(_this) {
      return function(evt) {
        _this.search_results_touchstart(evt);
      };
    })(this));
    this.search_results.bind('touchmove.chosen', (function(_this) {
      return function(evt) {
        _this.search_results_touchmove(evt);
      };
    })(this));
    this.search_results.bind('touchend.chosen', (function(_this) {
      return function(evt) {
        _this.search_results_touchend(evt);
      };
    })(this));
    this.form_field_jq.bind("chosen:updated.chosen", (function(_this) {
      return function(evt) {
        _this.results_update_field(evt);
      };
    })(this));
    this.form_field_jq.bind("chosen:activate.chosen", (function(_this) {
      return function(evt) {
        _this.activate_field(evt);
      };
    })(this));
    this.form_field_jq.bind("chosen:open.chosen", (function(_this) {
      return function(evt) {
        _this.container_mousedown(evt);
      };
    })(this));
    this.form_field_jq.bind("chosen:close.chosen", (function(_this) {
      return function(evt) {
        _this.input_blur(evt);
      };
    })(this));
    this.search_field.bind('blur.chosen', (function(_this) {
      return function(evt) {
        _this.input_blur(evt);
      };
    })(this));
    this.search_field.bind('keyup.chosen', (function(_this) {
      return function(evt) {
        _this.keyup_checker(evt);
      };
    })(this));
    this.search_field.bind('keydown.chosen', (function(_this) {
      return function(evt) {
        _this.keydown_checker(evt);
      };
    })(this));
    this.search_field.bind('focus.chosen', (function(_this) {
      return function(evt) {
        _this.input_focus(evt);
      };
    })(this));
    this.search_field.bind('cut.chosen', (function(_this) {
      return function(evt) {
        _this.clipboard_event_checker(evt);
      };
    })(this));
    this.search_field.bind('paste.chosen', (function(_this) {
      return function(evt) {
        _this.clipboard_event_checker(evt);
      };
    })(this));
    if (this.is_multiple) {
      return this.search_choices.bind('click.chosen', (function(_this) {
        return function(evt) {
          _this.choices_click(evt);
        };
      })(this));
    } else {
      return this.container.bind('click.chosen', function(evt) {
        evt.preventDefault();
      });
    }
  };

  Chosen.prototype.destroy = function() {
    $(this.container[0].ownerDocument).unbind("click.chosen", this.click_test_action);
    if (this.search_field[0].tabIndex) {
      this.form_field_jq[0].tabIndex = this.search_field[0].tabIndex;
    }
    this.container.remove();
    this.form_field_jq.removeData('chosen');
    return this.form_field_jq.show();
  };

  Chosen.prototype.search_field_disabled = function() {
    this.is_disabled = this.form_field_jq[0].disabled;
    if (this.is_disabled) {
      this.container.addClass('chosen-disabled');
      this.search_field[0].disabled = true;
      if (!this.is_multiple) {
        this.selected_item.unbind("focus.chosen", this.activate_action);
      }
      return this.close_field();
    } else {
      this.container.removeClass('chosen-disabled');
      this.search_field[0].disabled = false;
      if (!this.is_multiple) {
        return this.selected_item.bind("focus.chosen", this.activate_action);
      }
    }
  };

  Chosen.prototype.container_mousedown = function(evt) {
    if (!this.is_disabled) {
      if (evt && evt.type === "mousedown" && !this.results_showing) {
        evt.preventDefault();
      }
      if (!((evt != null) && ($(evt.target)).hasClass("search-choice-close"))) {
        if (!this.active_field) {
          if (this.is_multiple) {
            this.search_field.val("");
          }
          $(this.container[0].ownerDocument).bind('click.chosen', this.click_test_action);
          this.results_show();
        } else if (!this.is_multiple && evt && (($(evt.target)[0] === this.selected_item[0]) || $(evt.target).parents("a.chosen-single").length)) {
          evt.preventDefault();
          this.results_toggle();
        }
        return this.activate_field();
      }
    }
  };

  Chosen.prototype.container_mouseup = function(evt) {
    if (evt.target.nodeName === "ABBR" && !this.is_disabled) {
      return this.results_reset(evt);
    }
  };

  Chosen.prototype.search_results_mousewheel = function(evt) {
    var delta;
    if (evt.originalEvent) {
      delta = evt.originalEvent.deltaY || -evt.originalEvent.wheelDelta || evt.originalEvent.detail;
    }
    if (delta != null) {
      evt.preventDefault();
      if (evt.type === 'DOMMouseScroll') {
        delta = delta * 40;
      }
      return this.search_results.scrollTop(delta + this.search_results.scrollTop());
    }
  };

  Chosen.prototype.blur_test = function(evt) {
    if (!this.active_field && this.container.hasClass("chosen-container-active")) {
      return this.close_field();
    }
  };

  Chosen.prototype.close_field = function() {
    $(this.container[0].ownerDocument).unbind("click.chosen", this.click_test_action);
    this.active_field = false;
    this.results_hide();
    this.container.removeClass("chosen-container-active");
    this.clear_backstroke();
    this.show_search_field_default();
    return this.search_field_scale();
  };

  Chosen.prototype.activate_field = function() {
    this.container.addClass("chosen-container-active");
    this.active_field = true;
    this.search_field.val(this.search_field.val());
    return this.search_field.focus();
  };

  Chosen.prototype.test_active_click = function(evt) {
    var active_container;
    active_container = $(evt.target).closest('.chosen-container');
    if (active_container.length && this.container[0] === active_container[0]) {
      return this.active_field = true;
    } else {
      return this.close_field();
    }
  };

  Chosen.prototype.results_build = function() {
    this.parsing = true;
    this.selected_option_count = null;
    this.results_data = SelectParser.select_to_array(this.form_field);
    if (this.is_multiple) {
      this.search_choices.find("li.search-choice").remove();
    } else if (!this.is_multiple) {
      this.single_set_selected_text();
      if (this.disable_search || this.form_field.options.length <= this.disable_search_threshold) {
        this.search_field[0].readOnly = true;
        this.container.addClass("chosen-container-single-nosearch");
      } else {
        this.search_field[0].readOnly = false;
        this.container.removeClass("chosen-container-single-nosearch");
      }
    }
    this.update_results_content(this.results_option_build({
      first: true
    }));
    this.search_field_disabled();
    this.show_search_field_default();
    this.search_field_scale();
    return this.parsing = false;
  };

  Chosen.prototype.result_do_highlight = function(el) {
    var high_bottom, high_top, maxHeight, visible_bottom, visible_top;
    if (el.length) {
      this.result_clear_highlight();
      this.result_highlight = el;
      this.result_highlight.addClass("highlighted");
      maxHeight = parseInt(this.search_results.css("maxHeight"), 10);
      visible_top = this.search_results.scrollTop();
      visible_bottom = maxHeight + visible_top;
      high_top = this.result_highlight.position().top + this.search_results.scrollTop();
      high_bottom = high_top + this.result_highlight.outerHeight();
      if (high_bottom >= visible_bottom) {
        return this.search_results.scrollTop((high_bottom - maxHeight) > 0 ? high_bottom - maxHeight : 0);
      } else if (high_top < visible_top) {
        return this.search_results.scrollTop(high_top);
      }
    }
  };

  Chosen.prototype.result_clear_highlight = function() {
    if (this.result_highlight) {
      this.result_highlight.removeClass("highlighted");
    }
    return this.result_highlight = null;
  };

  Chosen.prototype.results_show = function() {
    if (this.is_multiple && this.max_selected_options <= this.choices_count()) {
      this.form_field_jq.trigger("chosen:maxselected", {
        chosen: this
      });
      return false;
    }
    this.container.addClass("chosen-with-drop");
    this.results_showing = true;
    this.search_field.focus();
    this.search_field.val(this.search_field.val());
    this.winnow_results();
    return this.form_field_jq.trigger("chosen:showing_dropdown", {
      chosen: this
    });
  };

  Chosen.prototype.update_results_content = function(content) {
    return this.search_results.html(content);
  };

  Chosen.prototype.results_hide = function() {
    if (this.results_showing) {
      this.result_clear_highlight();
      this.container.removeClass("chosen-with-drop");
      this.form_field_jq.trigger("chosen:hiding_dropdown", {
        chosen: this
      });
    }
    return this.results_showing = false;
  };

  Chosen.prototype.set_tab_index = function(el) {
    var ti;
    if (this.form_field.tabIndex) {
      ti = this.form_field.tabIndex;
      this.form_field.tabIndex = -1;
      return this.search_field[0].tabIndex = ti;
    }
  };

  Chosen.prototype.set_label_behavior = function() {
    this.form_field_label = this.form_field_jq.parents("label");
    if (!this.form_field_label.length && this.form_field.id.length) {
      this.form_field_label = $("label[for='" + this.form_field.id + "']");
    }
    if (this.form_field_label.length > 0) {
      return this.form_field_label.bind('click.chosen', (function(_this) {
        return function(evt) {
          if (_this.is_multiple) {
            return _this.container_mousedown(evt);
          } else {
            return _this.activate_field();
          }
        };
      })(this));
    }
  };

  Chosen.prototype.show_search_field_default = function() {
    if (this.is_multiple && this.choices_count() < 1 && !this.active_field) {
      this.search_field.val(this.default_text);
      return this.search_field.addClass("default");
    } else {
      this.search_field.val("");
      return this.search_field.removeClass("default");
    }
  };

  Chosen.prototype.search_results_mouseup = function(evt) {
    var target;
    target = $(evt.target).hasClass("active-result") ? $(evt.target) : $(evt.target).parents(".active-result").first();
    if (target.length) {
      this.result_highlight = target;
      this.result_select(evt);
      return this.search_field.focus();
    }
  };

  Chosen.prototype.search_results_mouseover = function(evt) {
    var target;
    target = $(evt.target).hasClass("active-result") ? $(evt.target) : $(evt.target).parents(".active-result").first();
    if (target) {
      return this.result_do_highlight(target);
    }
  };

  Chosen.prototype.search_results_mouseout = function(evt) {
    if ($(evt.target).hasClass("active-result" || $(evt.target).parents('.active-result').first())) {
      return this.result_clear_highlight();
    }
  };

  Chosen.prototype.choice_build = function(item) {
    var choice, close_link;
    choice = $('<li />', {
      "class": "search-choice"
    }).html("<span>" + (this.choice_label(item)) + "</span>");
    if (item.disabled) {
      choice.addClass('search-choice-disabled');
    } else {
      close_link = $('<a />', {
        "class": 'search-choice-close',
        'data-option-array-index': item.array_index
      });
      close_link.bind('click.chosen', (function(_this) {
        return function(evt) {
          return _this.choice_destroy_link_click(evt);
        };
      })(this));
      choice.append(close_link);
    }
    return this.search_container.before(choice);
  };

  Chosen.prototype.choice_destroy_link_click = function(evt) {
    evt.preventDefault();
    evt.stopPropagation();
    if (!this.is_disabled) {
      return this.choice_destroy($(evt.target));
    }
  };

  Chosen.prototype.choice_destroy = function(link) {
    if (this.result_deselect(link[0].getAttribute("data-option-array-index"))) {
      this.show_search_field_default();
      if (this.is_multiple && this.choices_count() > 0 && this.search_field.val().length < 1) {
        this.results_hide();
      }
      link.parents('li').first().remove();
      return this.search_field_scale();
    }
  };

  Chosen.prototype.results_reset = function() {
    this.reset_single_select_options();
    this.form_field.options[0].selected = true;
    this.single_set_selected_text();
    this.show_search_field_default();
    this.results_reset_cleanup();
    this.form_field_jq.trigger("change");
    if (this.active_field) {
      return this.results_hide();
    }
  };

  Chosen.prototype.results_reset_cleanup = function() {
    this.current_selectedIndex = this.form_field.selectedIndex;
    return this.selected_item.find("abbr").remove();
  };

  Chosen.prototype.result_select = function(evt) {
    var high, item;
    if (this.result_highlight) {
      high = this.result_highlight;
      this.result_clear_highlight();
      if (this.is_multiple && this.max_selected_options <= this.choices_count()) {
        this.form_field_jq.trigger("chosen:maxselected", {
          chosen: this
        });
        return false;
      }
      if (this.is_multiple) {
        high.removeClass("active-result");
      } else {
        this.reset_single_select_options();
      }
      high.addClass("result-selected");
      item = this.results_data[high[0].getAttribute("data-option-array-index")];
      item.selected = true;
      this.form_field.options[item.options_index].selected = true;
      this.selected_option_count = null;
      if (this.is_multiple) {
        this.choice_build(item);
      } else {
        this.single_set_selected_text(this.choice_label(item));
      }
      if (!((evt.metaKey || evt.ctrlKey) && this.is_multiple)) {
        this.results_hide();
      }
      this.show_search_field_default();
      if (this.is_multiple || this.form_field.selectedIndex !== this.current_selectedIndex) {
        this.form_field_jq.trigger("change", {
          'selected': this.form_field.options[item.options_index].value
        });
      }
      this.current_selectedIndex = this.form_field.selectedIndex;
      evt.preventDefault();
      return this.search_field_scale();
    }
  };

  Chosen.prototype.single_set_selected_text = function(text) {
    if (text == null) {
      text = this.default_text;
    }
    if (text === this.default_text) {
      this.selected_item.addClass("chosen-default");
    } else {
      this.single_deselect_control_build();
      this.selected_item.removeClass("chosen-default");
    }
    return this.selected_item.find("span").html(text);
  };

  Chosen.prototype.result_deselect = function(pos) {
    var result_data;
    result_data = this.results_data[pos];
    if (!this.form_field.options[result_data.options_index].disabled) {
      result_data.selected = false;
      this.form_field.options[result_data.options_index].selected = false;
      this.selected_option_count = null;
      this.result_clear_highlight();
      if (this.results_showing) {
        this.winnow_results();
      }
      this.form_field_jq.trigger("change", {
        deselected: this.form_field.options[result_data.options_index].value
      });
      this.search_field_scale();
      return true;
    } else {
      return false;
    }
  };

  Chosen.prototype.single_deselect_control_build = function() {
    if (!this.allow_single_deselect) {
      return;
    }
    if (!this.selected_item.find("abbr").length) {
      this.selected_item.find("span").first().after("<abbr class=\"search-choice-close\"></abbr>");
    }
    return this.selected_item.addClass("chosen-single-with-deselect");
  };

  Chosen.prototype.get_search_text = function() {
    return $('<div/>').text($.trim(this.search_field.val())).html();
  };

  Chosen.prototype.winnow_results_set_highlight = function() {
    var do_high, selected_results;
    selected_results = !this.is_multiple ? this.search_results.find(".result-selected.active-result") : [];
    do_high = selected_results.length ? selected_results.first() : this.search_results.find(".active-result").first();
    if (do_high != null) {
      return this.result_do_highlight(do_high);
    }
  };

  Chosen.prototype.no_results = function(terms) {
    var no_results_html;
    no_results_html = $('<li class="no-results">' + this.results_none_found + ' "<span></span>"</li>');
    no_results_html.find("span").first().html(terms);
    this.search_results.append(no_results_html);
    return this.form_field_jq.trigger("chosen:no_results", {
      chosen: this
    });
  };

  Chosen.prototype.no_results_clear = function() {
    return this.search_results.find(".no-results").remove();
  };

  Chosen.prototype.keydown_arrow = function() {
    var next_sib;
    if (this.results_showing && this.result_highlight) {
      next_sib = this.result_highlight.nextAll("li.active-result").first();
      if (next_sib) {
        return this.result_do_highlight(next_sib);
      }
    } else {
      return this.results_show();
    }
  };

  Chosen.prototype.keyup_arrow = function() {
    var prev_sibs;
    if (!this.results_showing && !this.is_multiple) {
      return this.results_show();
    } else if (this.result_highlight) {
      prev_sibs = this.result_highlight.prevAll("li.active-result");
      if (prev_sibs.length) {
        return this.result_do_highlight(prev_sibs.first());
      } else {
        if (this.choices_count() > 0) {
          this.results_hide();
        }
        return this.result_clear_highlight();
      }
    }
  };

  Chosen.prototype.keydown_backstroke = function() {
    var next_available_destroy;
    if (this.pending_backstroke) {
      this.choice_destroy(this.pending_backstroke.find("a").first());
      return this.clear_backstroke();
    } else {
      next_available_destroy = this.search_container.siblings("li.search-choice").last();
      if (next_available_destroy.length && !next_available_destroy.hasClass("search-choice-disabled")) {
        this.pending_backstroke = next_available_destroy;
        if (this.single_backstroke_delete) {
          return this.keydown_backstroke();
        } else {
          return this.pending_backstroke.addClass("search-choice-focus");
        }
      }
    }
  };

  Chosen.prototype.clear_backstroke = function() {
    if (this.pending_backstroke) {
      this.pending_backstroke.removeClass("search-choice-focus");
    }
    return this.pending_backstroke = null;
  };

  Chosen.prototype.keydown_checker = function(evt) {
    var ref, stroke;
    stroke = (ref = evt.which) != null ? ref : evt.keyCode;
    this.search_field_scale();
    if (stroke !== 8 && this.pending_backstroke) {
      this.clear_backstroke();
    }
    switch (stroke) {
      case 8:
        this.backstroke_length = this.search_field.val().length;
        break;
      case 9:
        if (this.results_showing && !this.is_multiple) {
          this.result_select(evt);
        }
        this.mouse_on_container = false;
        break;
      case 13:
        if (this.results_showing) {
          evt.preventDefault();
        }
        break;
      case 32:
        if (this.disable_search) {
          evt.preventDefault();
        }
        break;
      case 38:
        evt.preventDefault();
        this.keyup_arrow();
        break;
      case 40:
        evt.preventDefault();
        this.keydown_arrow();
        break;
    }
  };

  Chosen.prototype.search_field_scale = function() {
    var div, f_width, h, i, len, style, style_block, styles, w;
    if (this.is_multiple) {
      h = 0;
      w = 0;
      style_block = "position:absolute; left: -1000px; top: -1000px; display:none;";
      styles = ['font-size', 'font-style', 'font-weight', 'font-family', 'line-height', 'text-transform', 'letter-spacing'];
      for (i = 0, len = styles.length; i < len; i++) {
        style = styles[i];
        style_block += style + ":" + this.search_field.css(style) + ";";
      }
      div = $('<div />', {
        'style': style_block
      });
      div.text(this.search_field.val());
      $('body').append(div);
      w = div.width() + 25;
      div.remove();
      f_width = this.container.outerWidth();
      if (w > f_width - 10) {
        w = f_width - 10;
      }
      return this.search_field.css({
        'width': w + 'px'
      });
    }
  };

  return Chosen;

})(AbstractChosen);
