module.exports = (grunt) ->
  require('load-grunt-tasks')(grunt);

  version = ->
    grunt.file.readJSON("package.json").version
  version_tag = ->
    "v#{version()}"

  grunt.initConfig
    pkg: grunt.file.readJSON("package.json")
    comments: """
/*!
chosen4chinese, chosen4chinese 是在chosen https://github.com/harvesthq/chosen 的基础上专门针对中文的改进。
Version <%= pkg.version %>
代码 at https://github.com/doukit/chosen4chinese
This file is generated by `grunt build`, do not edit it by hand.
*/
\n
"""
    minified_comments: "/* Chosen #{version_tag()} | (c) 2011-<%= grunt.template.today('yyyy') %> by Harvest | MIT License, https://github.com/harvesthq/chosen/blob/master/LICENSE.md */\n"

    concat:
      options:
        banner: "<%= comments %>"
      jquery:
        src: ["lib/chosen.jquery.js"]
        dest: "lib/chosen.jquery.js"
      proto:
        src: ["lib/chosen.proto.js"]
        dest: "lib/chosen.proto.js"
      css:
        src: ["lib/css/chosen.css"]
        dest: "lib/css/chosen.css"

    coffee:
      options:
        join: true
      compile:
        files:
          'lib/chosen.jquery.js': ['src/base/select-parser.coffee', 'src/base/abstract-chosen.coffee', 'src/pinyin.coffee', 'src/chosen.jquery.coffee']
          'lib/chosen.proto.js': ['src/base/select-parser.coffee', 'src/base/abstract-chosen.coffee', 'src/chosen.proto.coffee']

    uglify:
      options:
        mangle:
          except: ['jQuery', 'AbstractChosen', 'Chosen', 'SelectParser']
        banner: "<%= minified_comments %>"
      minified_chosen_js:
        files:
          'lib/chosen.jquery.min.js': ['lib/chosen.jquery.js']
          'lib/chosen.proto.min.js': ['lib/chosen.proto.js']

    compass:
      chosen_css:
        options:
          bundleExec: true
          specify: ['sass/chosen.scss']

    cssmin:
      minified_chosen_css:
        options:
          banner: "<%= minified_comments %>"
          keepSpecialComments: 0
        src: 'lib/css/chosen.css'
        dest: 'lib/css/chosen.min.css'

    watch:
      scripts:
        files: ['coffee/**/*.coffee', 'sass/*.scss']
        tasks: ['build']

  grunt.registerTask 'default', ['build']
  grunt.registerTask 'build', ['coffee', 'concat', 'uglify']
  grunt.registerTask 'test',  ['coffee']
